authentication/admin.py
authentication/apps.py
authentication/models.py
authentication/tests.py
authentication/views.py

He extendido la clase de User de django para añadirle el campo dieta y he importado los métodos que permiten controlar qué tipo de usuarios pueden acceder o no a una vista, los he explicado en el views.py del módulo de authentication que he creado para esta issue #6 .

feat: Configuración inicial del usuario y el admin

---

Eatsy/urls.py
product/urls.py
product/views.py

Se ha añadido la vista, configurado las URLs y añadido el template. Issue #43

feat: Vista para mostrar detalles del producto

---

product/urls.py
product/views.py

Se ha añadido la vista, configurado las URLs y añadido el template. Issue #42

feat: Vista de listado de productos

---

product/forms.py
product/urls.py
product/views.py

Añadido el método para la búsqueda, conguración de las URLs y añadido el forms.py. Issues #10

feat: Controladores para la búsqueda de productos

---

product/views.py

Arreglado metodo de validación formulario y  variable con los datos para el template

fix: Controladores para la búsqueda de productos

---

product/admin.py
product/forms.py
product/models.py
product/urls.py
product/views.py

Acabado el controlador de la creación de un reporte, entidades y formularios relacionados.

feat: Desarrollar controladores y servicios para reportar un producto

---

product/templates/products/base.html
product/templates/products/list.html
product/templates/products/show.html

Se ha implementado un archivo base.html del que extenderán el resto y que centraliza el menú y el footer para ser reutilizados

feat: Plantilla base para menú y footer

---

product/forms.py
product/templates/products/show.html
product/urls.py
product/views.py
static/estilo/style.css

para hacer el pop-up debia estar el controlador del post en el propio show por eso se ha cambiado de sitio. closes #20

feat: añadido formulario del reporte

---

product/forms.py
product/templates/products/create.html
product/views.py

Se ha aplicado el css y se ha refactorizado el formulario, ademas se ha añadido un botón de cancelar y un alerta. closes #15

feat: Aplicación CSS y refactoriazad la vista de crear producto

---

product/admin.py
product/models.py

Pull request para mergear el nuevo modelo de aportación con los errores anteriores corregidos.

60 juaferfer11

---

.gitignore
Procfile

Se han añadido las migrations al archivo gitignore para que no se añadan y se ha actualizado el archivo Procfile para que se ejecite correctamente Heroku

fix:Añadido a gitignore las migrations y modificado el procfile

---

product/views.py
requirements.txt

Se añade el paquete pillow al requirements y se adapta la ruta de las imágenes. #30

fix: paquete requirements, ruta imágenes media

---

product/forms.py
product/urls.py
product/views.py

Creación del metodo para borrar aportaciones, así como incluirlo en el urls.py, eliminacion de duplicaciones en un formulario. Issue #25

feat: Añadida la funcionalidad de borrar aportaciones

---

product/forms.py
product/templates/products/review.html
product/views.py

también se ha hecho responsive. closes #29.

feat: se ha adecuado el formulario de review para administrador

---

product/views.py

Antes de borrar se comprueba que pertenezca al usuario que envía la petición #26

feat: solo borrar comentarios propios

---

product/templates/products/base.html
product/templates/products/list.html
product/templates/products/map.html
product/templates/products/show.html
static/estilo/style.css

Sobre todo es el list y en menor medida el show.

feat: ahora estas vistan son responsive. Issue #93.

---

product/forms.py
product/views.py

Añadido método en el views y añadido también el formulario. Issue #31

feat: Desarrollar controladores para añadir una ubicación nueva al producto.

---

product/templates/products/list.html
product/views.py

Se ha implementado un menú desplegable donde el administrador puede filtrar los productos entre aquellos aceptados y los que están pendiente de revisión. #28

feat: Filtrado de productos por estado para admin

---

product/forms.py
product/templates/products/list.html
product/views.py

Se ha implementado una barra de búsqueda por nombre y diversos filtros para los productos listados. #96 #95

feat: Barra de búsqueda y filtros en listado

---

product/views.py

El administrador puede revisar los productos independientemente de su estado. También se valida que nombreComercio no sea blanco si se selecciona ubicación en el mapa #30

fix: se pueden revisar productos aceptados también

---

product/templates/reports/list.html
product/urls.py
product/views.py

He modificado el archivo de views para que permita listar los reportes de los diferentes usuarios al administrador. Issue #44

feat: He creado el listado de reportes

---

product/forms.py
product/models.py
product/urls.py
product/views.py

Creado el formulario,su metodo en el views y su URL, tambien se realizo un cambio en el modelo. Issue #36

feat: Crear controladores para revisar el reporte.

---

product/templates/reports/list.html
static/estilo/style.css

Se ha implementado la vista del listado de productos reportados por los usuarios.

feat: Añadido el listado de reportes

---

Eatsy/settings.py
product/forms.py
product/models.py
product/templates/products/list.html
product/templates/products/review.html
product/templates/products/show.html
product/views.py
requirements.txt

fix: arreglado revisión del producto

30 javgarcer

---

product/templates/reports/list.html
product/urls.py
product/views.py
static/estilo/style.css

Se hace através de un modal en el propio listado de reportes. Issue #35.

feat: ahora el admin puede aprobar y denegar reportes

---

product/templates/products/base.html
product/templates/products/list.html
product/templates/products/show.html
product/views.py
static/js/rating.js

Se han añadido el precio y valoración media autocalculado. Se ha incorporado el favicon. Se han añadido las dietas a la vista individual y al listado de productos. close #122

fix: precio y valoración media añadidos en la vista individual. Dietas añadidas en vista individual y listado

---

authentication/admin.py
authentication/models.py
product/admin.py
product/models.py
product/views.py

He terminado la tarea de arreglar el listado de reportes para que se muestren solo los pendientes y de cambiar el atributo de dieta de perfil a un manytomany. Issue #118

Merge de 118-juaferfer11 a develop

---

product/templates/products/base.html
product/templates/products/list.html
product/templates/products/show.html
static/estilo/style.css

También se ha arreglado el responsive de la página. Issue #126.

fix: se han linkeado todos los botones

---

product/templates/products/show.html
product/views.py

Listado de comentarios de un producto en su vista. #132

feat: Listado de comentarios de un producto

---

Eatsy/urls.py
Eatsy/views.py
product/templates/products/paginaprincipal.html
product/templates/products/subscribe.html
static/estilo/style.css

Se ha creado la vista de suscripción con un bóton para realizar el pago close #134

feat: Vista de suscripción creada

---

product/templates/products/show.html

Adicionalmente también verá un mensaje advirtiendo que el producto que está visionando está en revisión. closes #146

feat: ahora el admin no ve los botones

---

.travis.yml
authentication/tests.py
main/tests.py
product/tests.py

Se han añadido las pruebas de modelo para ubicación, producto, reporte, aportación, valoración y perfil.

Test: Se han añadido las pruebas de modelo

---

product/templates/products/list.html
product/templates/products/show.html
product/views.py
static/estilo/style.css

También se ha arreglado un poco el estilo del listado y el show.

Arreglado problemas de paginación

---

product/templates/products/subscribe.html

Se ha creado una vista para el mock-up de registro de usuario close #157

feat: Creación de mock-up de registro de usuario

---

product/tests_api.py

Se ha terminado de implementar los tests de API en su totalidad, incluyendo aquellos que acceden a los distintos endpoints del sistema como aquellos que crean entidades como productos, comentarios o reportes. close #39

test: Tests de API finalizados

---

Eatsy/views.py
authentication/tests.py
authentication/views.py
main/admin.py
main/models.py
main/tests.py
main/views.py
product/forms.py
product/models.py
product/tests.py
product/views.py
static/estilo/style.css
static/js/rating.js

Se han solucionado algunos errores indicados por Codacy. #155

fix: Refactorización

---

info.yml

Se ha creado el archivo info.yml para que sea posible auditar el proyecto por parte del sistema Governify. Issue #191

doc: Añadido fichero de configuración de Governify

---

product/templates/products/subscribe.html
product/tests_selenium.py

Se ha implementado el html y el css de la vista para registrar a los usuarios. Issue #169

feat: Añadida la vista del registro de usuario

---

product/templates/products/base.html
product/templates/products/list.html
product/templates/products/paginaprincipal.html
product/templates/products/show.html
product/templates/products/subscribe.html
static/estilo/style.css

Se han cambiado los colores, fuentes, y otros pequeños detalles para dar un nuevo estilo a la web, más parecido al usado por el equipo en las presentaciones. Issue #185

fix: arreglado el estilo

---

Eatsy/urls.py
authentication/forms.py
authentication/models.py
authentication/templates/signUp.html
authentication/urls.py
authentication/views.py
product/templates/products/paginaprincipal.html

Se ha implementado la view para registrar un usuario, el form y también se ha cambiado el template al módulo de authentication. Issue #172

feat: Controladores para el registro

---

Eatsy/urls.py
Eatsy/views.py
authentication/forms.py
authentication/template/login.html
authentication/views.py
product/forms.py
product/templates/products/login.html
product/templates/products/paginaprincipal.html

Se ha implementado la view para iniciar sesion, el form y también se ha cambiado el template al módulo de authentication. Issue #166

feat: Creación inicio de sesión

---

Eatsy/urls.py
authentication/forms.py
authentication/templates/login.html
authentication/urls.py
authentication/views.py
product/templates/products/base.html
product/templates/products/paginaprincipal.html

Se implementan los controladores para iniciar sesión y cerrarla. Se adaptan los enlaces. Issue #168

feat: Controladores de inicio de sesión

---

authentication/urls.py
authentication/views.py

Se ha añadido un nuevo método para el show del perfil, así como, su path necesario en las urls. Issue #184

feat: Controlador para acceder al perfil

---

authentication/templates/subscribe.html
authentication/urls.py
authentication/views.py
static/estilo/style.css

Se ha añadido el formulario y también añadido la ruta. closes #174.

feat: añadida formulario de collección de pagos

---

authentication/forms.py
authentication/templates/perfil.html
authentication/urls.py
authentication/views.py

Se añaden los controladores, el formulario y la vista inicial sin retocar para la modificación de datos personales. Issue #207

feat: Controladores para modificar perfil

---

authentication/forms.py
authentication/templates/perfil.html

Se ha realizado la vista para modificar el perfil de los usuarios. Issue #206

feat: terminada la vista de edición de perfil

---

Eatsy/views.py
authentication/forms.py

Se ha solucionado el problema de los espacios en las password, se ha corregido la errata que aparecía en los mensajes de validación de las password y se ha borrado el login del archivo views.py del módulo Eatsy. #204

fix: Solucionado problema password y mensaje

---

authentication/forms.py
authentication/templates/perfil.html
authentication/templates/resetPass.html
authentication/views.py

Se acaba la funcionalidad de cambiar contraseña desde el perfil del usuario. Issue #209

feat: Controladores de cambio de contraseña

---

product/forms.py
product/templates/products/create.html
product/templates/products/review.html
static/estilo/style.css

Se han cambiado el css de los formularios de creación de productos y revisión de productos, además se modificado el create para que sea web responsive. #205

fix: Css cambiado y web responsive del create

---

product/forms.py
product/tests_api.py
product/views.py

Los filtros cargados por defecto son los del usuario logeado. #189

feat: Mejorar filtrado de productos

---

product/templates/products/show.html

Ahora los comentarios incluyen nombre de usuario y fehca. Issue #188

fix: comentarios completos

---

authentication/views.py
product/templates/products/paginaprincipal.html
product/tests_api.py
product/tests_selenium.py
product/views.py

Se han añadido los decoradores pertinentes en el views.py de productos y autenticación. Issue #186

feat: Restringir vistas a usuarios no hayan pagado 

---

authentication/templates/subscribe.html

Se ha incluido el código correspondiente a la gestión de pagos para métodos que requieran una autenticación bancaria externa. Issue #180

feat: Gestionar autenticación de pagos 

---

authentication/templates/subscribe.html
authentication/urls.py
authentication/views.py
static/estilo/style.css

Controladas las tarjetas canceladas, además de dar un poco de estilo a la página de suscripción, Issue #176

Franpb14yjuaferfer11 #176

---

product/templates/products/create.html
product/templates/products/map.html
static/estilo/style.css

Ahora en el formulario para crear un producto se distingue bien entre supermercado o no, también se ha añadido una preview de la imagen, y en el mapa se quita el zoom cuando se señala un supermercado, adicionalmente se ha cambiado el estilo de los botones en el show. Issue #221.

fix: Cambiado el formulario de create y cosas del map

---

product/tests_api.py
product/views.py

Se han corregido los métodos del views para que asocien correctamente a cada usuario al realizar las funcionalidades, además se han arreglado un par de "TODO" más y se han comentado los test que daban problemas. Issue #187

fix: Cambios en métodos de BackEnd.

---

authentication/templates/subscribe.html
authentication/urls.py
authentication/views.py

Ahora se da acceso al servicio una vez comprada una suscripción. #178

feat: Dar acceso al servicio

---

authentication/templates/subscribe.html
authentication/views.py

Añadido un mes gratuito cuando el usuario compra una suscripción por primera vez.
También se comprueba el estado de suscripción actual cada vez que el usuario se logea. #177

feat: Añadir mes gratuito

---

authentication/templates/perfil.html
authentication/urls.py
authentication/views.py
product/templates/products/list.html

feat: Cancelar suscripción
Se ha finalizado la implementación de la funcionalidad de cancelar suscripción. Issue #179

feat: Cancelar suscripción

---

authentication/forms.py

Se han modificado el formulario de registro para que resulte más estético. #222

fix: Correccion estilo formulario de registro

---

authentication/templates/perfil.html
authentication/templates/subscribe.html

Se han corregido los errores menores de la funcionalidad pagos. Issue #235

fix: Errores menores de pagos corregidos

---

product/tests_api.py
product/tests_selenium.py

Se han corregidos los errores de las pruebas. Issue #171

fix: Errores de pruebas corregidos

---

authentication/templates/perfil.html
authentication/templates/subscribe.html

Se han corregido fallos ortográficos de algunas vistas. Se ha dado estilo al botoón activar cuenta y cancelar suscripción. Se ha añadido un mensaje de avisa en el registro del pago. Issue #238

fix:Mejoras estéticas de la aplicación

---

product/templates/products/paginaprincipal.html
product/views.py
static/estilo/style.css

Se ha arreglado el error de sintaxis del views y comprobado el funcionamiento de todos los métodos. Issue #245

fix: Arreglar métodos del views 

---

product/templates/products/list.html

Ahora el botón de borrar filtros borra los filtros y se muestra incluso cuando los filtros por defecto del usuario están siendo aplicados. #237

fix: Error en el filtrado de productos

---

Eatsy/settings.py
Eatsy/urls.py
recipe/admin.py
recipe/apps.py
recipe/models.py
recipe/tests.py
recipe/urls.py
recipe/views.py

Se crea la aplicación para recetas, su modelo y el controlador para el show. También se controla el acceso. Issue #268

feat: Configuracion inicial de recetas

---

product/views.py

Modificado el controlador para que se envíen las recetas del producto. Issue #269

feat: Controlador show de producto modificado

---

authentication/templates/login.html
authentication/templates/perfil.html
authentication/templates/resetPass.html
authentication/templates/signUp.html
authentication/templates/subscribe.html
product/templates/products/create.html
product/templates/products/review.html
product/templates/products/show.html

Se han cambiado botones y añadido textos explicativos. Issue #255

feat: mejora general de los productos

---

Eatsy/urls.py
Eatsy/views.py
product/templates/products/aboutUs.html
product/templates/products/paginaprincipal.html
static/estilo/style.css

Se ha  añadido el footer y se ha aplicado el responsive tanto en la pagina principal como en el aboutUs. Issue #262

feat: Vista About Us 

---

product/templates/products/404.html
product/templates/products/aboutUs.html
product/templates/products/base.html
product/templates/products/errorView.html
product/templates/products/paginaprincipal.html
product/templates/products/show.html
product/urls.py
product/views.py
static/estilo/style.css

Añadido los enlaces al footer en todas las vistas, incluido también su webresponsive y corrección de las faltas de ortografía. Issue #265

fix: Mejora footer

---

recipe/templates/recipes/show.html

Se ha implementado la vista de "show" de las recetas, de forma que se muestra su imagen, su cuerpo de texto y los ingredientes o productos que pertenecen a esa receta. Issue #271

feat: Vista de Recetas #271

---

recipe/forms.py
recipe/templates/recipes/create.html
recipe/urls.py
recipe/views.py

Se ha creado el formulario para que el usuario pueda registrar nuevas recetas en el sistema. Issue #273

feat: Vista formulario crear receta #273

---

recipe/forms.py
recipe/templates/recipes/create.html
recipe/views.py

No se pueden obtener los productos en el formulario, se pasan desde la vista. Issue #272

fix: solucionado error en Travis

---

shoppingList/templates/shoppingList/show.html
static/estilo/style.css

Se ha creado una vista para la lista de la compra, donde se puede ver el producto y su nombre, y eliminarlos. Issue #276

feat: Creada la vista lista de la compra

---

product/templates/products/list.html
product/templates/products/show.html

Se ha añadido el logo de los alergenos y restricciones alimenticias a las vistas de lista e individual de productos.Issue #11

feat: Imagen alérgenos en vistas y listas

---

authentication/templates/signUp.html
product/templates/products/aboutUs.html
product/templates/products/base.html
product/templates/products/contactUs.html
product/templates/products/paginaprincipal.html
product/templates/products/privacyPolicy.html
product/templates/products/show.html
product/views.py
recipe/templates/recipes/show.html

Se han añadido las políticas de privacidad tanto en el registro como en la página de políticas de privacidad. Se han corregido algunos errores menores en la aplicación. Issue #306

feat: Añadidas políticas de privacidad

---

shoppingList/urls.py
shoppingList/views.py

He creado el controlador que vacía la lista. Issue #280

feat: Controlador vaciar lista

---

shoppingList/urls.py
shoppingList/views.py

Se ha creado el controlador para eliminar un producto de la lista de la compra. Issue #279

feat: Controlador eliminar producto de la lista

---

product/templates/products/aboutUs.html
product/templates/products/base.html
product/templates/products/contactUs.html
product/templates/products/list.html
product/templates/products/paginaprincipal.html
product/templates/products/privacyPolicy.html
product/templates/products/show.html
recipe/templates/recipes/show.html
static/estilo/style.css

Además se han introducido algunos cambios como en about us fondo transparente para las fotos o poner fondo blanco en privacidad cuando se hace pequeño. closes #311.

fix: arreglado todo lo de la Issue #311

---

product/templates/products/create.html
product/templates/products/review.html

Se han añadido aclaraciones en los formularios de creación y edición del producto para poner varias etiquetas. Issue #258

feat: Adición de dos comentarios

---

product/forms.py
product/models.py
product/templates/products/list.html
product/tests_api.py
product/views.py

He añadido el filtrado por ubicaciones. Sin embargo, no he podido añadir el logo al filtro de productos.
También he quitado algunas dietas hard-codeadas de algunos modelos, ahora las lee de la base de datos. Issue #261

fat: Mejora filtrado

---

product/templates/products/aboutUs.html
product/templates/products/base.html
product/templates/products/contactUs.html
product/templates/products/paginaprincipal.html
product/templates/products/privacyPolicy.html
static/estilo/style.css

Se ha cambiado el estilo del footer, se ha mejorado el web responsive, se ha cambiado el tamaño de los títulos y se han corregido las faltas de ortografía en la política de privacidad. Issue #264

fix: Vista Políticas de Privacidad

---

authentication/templates/subscribe.html
authentication/urls.py
authentication/views.py
product/templates/products/show.html
product/views.py

Se ha añadido un botón para que el usuario pueda borrar su comentario. Issue #267

feat: Añadido botón de borrar comentario

---

static/estilo/style.css

Se han añadido los iconos de las intolerancias al filtrado. Issue #261

feat: Mejorar filtrado

---

authentication/templates/subscribe.html
product/templates/products/show.html
product/views.py
shoppingList/templates/shoppingList/show.html
shoppingList/views.py

Se han arreglado los errores especificados en la descripción. El error de pagos habrá que comprobar en el despliegue si se ha solucionado. Issue #318

fix: Arreglos en el funcionamiento

---

product/forms.py
product/templates/products/list.html
product/templates/products/review.html
static/estilo/style.css

Se han arreglado fallos menores en la creación de reportes de un producto y se ha modificado ligeramente la vista de listado. Issue #321

fix: Solventados fallos en el reporte y arreglos en el listado

---

product/tests_api.py

Se han añadido todos los tests pertenecientes a las nuevas funcionalidades de las áreas de recetas, lista de la compra y enlaces del footer. Issue #326

test: Pruebas para API

---

authentication/tests_selenium.py
product/tests_api.py
product/tests_selenium.py
static/estilo/style.css

Se han añadido las pruebas de selenium. Issue #328

Pruebas de Selenium

---

Eatsy/views.py
authentication/forms.py
authentication/tests_selenium.py
product/forms.py
product/models.py
product/templates/products/list.html
product/tests.py
product/tests_api.py
product/tests_selenium.py
product/urls.py
product/views.py
recipe/forms.py
recipe/tests.py
recipe/views.py
shoppingList/tests.py
shoppingList/urls.py
shoppingList/views.py
static/estilo/style.css

Se ha refactorizado el código para mejorar la calidad del mismo. Issue #330

refactor: Refactorización Sprint 3

---

product/templates/products/list.html
static/estilo/style.css

también se ha mejorado la paginación. closes #334.

fix: ahora funcionan las fotos en firefox

---

authentication/forms.py
authentication/views.py
product/templates/products/show.html
recipe/views.py
static/estilo/style.css

Se han cambiado los enumerados de los formularios por relaciones al modelo Dieta. Ahora se marca por defecto el producto del que se quiere hacer la receta. Issue #335

fix: Mejora de dietas

---

product/forms.py
product/models.py
product/templates/products/404.html
product/templates/products/base.html
product/templates/products/create.html
product/templates/products/errorView.html
product/templates/products/review.html
product/templates/products/show.html
product/views.py

Se han añadido los valores nutricionales a los productos. También se ha corregido la versión de Bootstrap.

feat: Añadir valores nutricionales

---

product/forms.py
product/templates/products/create.html
product/templates/products/list.html
product/templates/products/review.html
product/views.py

Se ha añadido la capacidad de filtrar productos por categoría. Issue #338

feat: Filtrado categoría de producto

---

Eatsy/settings.py
product/forms.py

Se ha agregado la congifuración necesaria en settings.py para que, en determinadas ocasiones, los errores de CSRF sean controlados. También se ha agregado una linea para el atributo 'categorias' en forms.py. Issue #337

feat: Mejora en settings

---

product/templates/products/list.html

se ha añadido un estilo que esta solo en el list para no interferir con el resto de checkboxs. closes #349.

fix: ya está arreglado el checkbox en firefox
